### PR TITLE
Updated the Mapbox access token

### PR DESCRIPTION
**Pull request by jinalfoflia**
With reference to this comment - https://github.com/osm-in/openstreetmap.in/issues/21#issuecomment-461444165, have changed the access token to the new one.

cc: @geohacker

### CODE REVIEW

**Comment by karthikb351** [comment]
@geohacker @planemad _gentle nudge_

Related: https://github.com/osm-in/openstreetmap.in/issues/29

**Comment by planemad** [comment]
@geohacker this needs a redeploy?

**Comment by geohacker** [comment]
I deployed just now, sorry about the delay. But looks like a tileset/style is missing or running into a 401 from @planemad's account.

**Comment by planemad** [comment]
@geohacker The deployed site is still [requesting using the expired token](https://a.tiles.mapbox.com/v4/planemad.9acc2036.json?access_token=pk.eyJ1IjoiamluYWxmb2ZsaWEiLCJhIjoiY2psejFtZG8wMWhnMjNwcGFqdTNjaGF2MCJ9.ZQVAZAw8Xtg4H2YSuG4PlA&secure) while it should have been using [this one](https://a.tiles.mapbox.com/v4/planemad.9acc2036.json?access_token=pk.eyJ1Ijoib3NtLWluIiwiYSI6ImNqcnVxMTNrNTJwbHc0M250anUyOW81MjgifQ.cZnvZEyWT5AzNeO3ajg5tg&secure)

**Comment by geohacker** [comment]
You're right @planemad. I missed the jekyll build. We could move this to Github for sure and point the domain to a github cname - just a bunch of work that I've no bandwidth for at the moment.

**Pull request merged**
