### PR TITLE
Osmhack changes

### PR DESCRIPTION
**Pull request by planemad**
By @rvgpl:
- Fix broken logo
- Jekyll restructure
- Minor CSS improvements

screenshot 2016-07-03 12 20 30

cc @geohacker @batpad

### CODE REVIEW

**Comment by planemad** [comment]
@rvgpl how are the breakpoints being used currently?

**Comment by rvgpl** [comment]
@planemad All CSS is mobile-first so breakpoints are used when the device is not mobile. The current breakpoints are defined in `grids.scss`, I used [breakpoint-sass](http://breakpoint-sass.com/) to write easier media queries. 

So once the device is `$tablet` or `$pc` width which is defined in `grids.scss` the CSS is applied to that particular class. 

Usage: 
```scss 
@include breakpoint($tablet) {
   ....//tablet styles
}
@include breakpoint($pc) {
   .... //Desktop styles
}
```

**Comment by planemad** [comment]
Needs a redeploy

cc @batpad

**Comment by geohacker** [comment]
@planemad deploy done - http://openstreetmap.in/#5/22.150/79.081

Thank you @planemad @rvgpl! 🙇

**Pull request merged**
